-- Create profile_lists table
CREATE TABLE profile_lists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Create index for faster queries
CREATE INDEX idx_profile_lists_user_id ON profile_lists(user_id);

-- Modify saved_profiles to support list association
ALTER TABLE saved_profiles 
ADD COLUMN list_id BIGINT REFERENCES profile_lists(id) ON DELETE SET NULL;

-- Enable Row Level Security for the new table
ALTER TABLE profile_lists ENABLE ROW LEVEL SECURITY;

-- Create policies to restrict access
CREATE POLICY "Users can manage their own lists" ON profile_lists
    FOR ALL USING (auth.uid() = user_id);
